version: '3.1'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drone
      MYSQL_USER: suds
      MYSQL_PASSWORD: suds
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
  web:
    image: drones
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/drone
      SPRING_DATASOURCE_USERNAME: suds
      SPRING_DATASOURCE_PASSWORD: suds
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db_data: {}